#!/usr/bin/env bash

set -euo pipefail

# jq: error (at <stdin>:0): null (null) and number (1) cannot be divided
jq -r '.databases[] | [.name, .storage_type, .storage_used, (.storage_used / .storage_size)] | @csv'
